Fixed error: "too few arguments to function ‘void dgetrs_..."
Some of the recent interfaces of LAPACK libraries require that the length of the char* array should be passed as the last argument (size_t = 1). They usually provide the old interface by mangling names by dgetrs_ -> LAPACK_dgetrs, which is used in this fix